var navbar = document.getElementById("menu");
navbar.innerHTML += '<a href="/" style="float:right">Back to base</a>\n';
navbar.innerHTML += '<a href="/eT/eTP.html">Prospectus</a>\n';
navbar.innerHTML += '<a href="/eT/fi/fi.html">Infection delays</a>\n';
navbar.innerHTML += '<a href="/eT/SIR/SIR.html">SIR model and covid-19</a>\n';
navbar.innerHTML += '<a href="/eT/Power/Power.html">Powering<sup>up</sup></a>\n';
navbar.innerHTML += '<a href="/eT/Branching/Branching.html">Bugs, bunnies . . .</a>\n';
navbar.innerHTML += '<a href="/eT/Logjam/logjam.html">Logjam</a>\n';
navbar.innerHTML += '<a href="/eT/Backlog/backlog.html">Backlog</a>\n';
navbar.innerHTML += '<a href="/eT/Basic analysis/basic.html">Basic analysis</a>\n';
