var navbar = document.getElementById("menu");
navbar.innerHTML += '<a href="/" style="float:right">Back to base</a>\n';
navbar.innerHTML += '<a href="/eT">Prospectus</a>\n';
navbar.innerHTML += '<a href="/eT/Power/Power.html">Powering<sup>up</sup></a>\n';
navbar.innerHTML += '<a href="/eT/Backlog/backlog.html">Backlog</a>\n';
navbar.innerHTML += '<div class="dropdown"><button class="dropbtn">Logjam ▼</button><div class="dropdown-content"><a href="/eT/Logjam/logjam0.html">0 Introduction</a><a href="/eT/Logjam/logjam1.html">1 So what are logarithms?</a><a href="/eT/Logjam/logjam2.html">2 Power relations</a><a href="/eT/Logjam/logjam3.html">3 Tabling some vulgarity</a><a href="/eT/Logjam/logjam4.html">4 Compound uselessness</a><a href="/eT/Logjam/logjam5.html">5 I hear you</a><a href="/eT/Logjam/logjam6.html">6 Graph-o-log-y or log-graph-y?</a><a href="/eT/Logjam/logjam7.html">7 What the frack is a slide-rule?</a></div></div>\n'
navbar.innerHTML += '<div class="dropdown"><button class="dropbtn">Analysis ▼</button><div class="dropdown-content"><a href="/eT/Basic analysis/basic.html">Basic</a><a href="/eT/Richardson/Richardson.html">Richardson extrapolation</a></div></div>\n'
navbar.innerHTML += '<div class="dropdown"><button class="dropbtn">Bugs, bunnies . . . ▼</button><div class="dropdown-content"><a href="/eT/Branching/Branching1.html">1 Branches</a><a href="/eT/Branching/Branching2.html">2 Wascally wabbits</a><a href="/eT/Branching/Branching3.html">3 Boom!</a></div></div>\n'
navbar.innerHTML += '<div class="dropdown"><button class="dropbtn">Infection delays  . . . ▼</button><div class="dropdown-content"><a href="/eT/fi/fi0.html">Introduction</a><a href="/eT/fi/fi1.html">Example 1: Two-day delay</a><a href="/eT/fi/fi2.html">Example 2: Three-day delay</a><a href="/eT/fi/fi3.html">Example 3: Interactive</a><a href="/eT/fi/fi4.html">Example 4: Drowning and waving</a></div></div>\n'
navbar.innerHTML += '<div class="dropdown"><button class="dropbtn">SIR models  . . . ▼</button><div class="dropdown-content"><a href="/eT/SIR/SIR0.html">Introduction</a><a href="/eT/SIR/SIR1.html">1 Exponential growth</a><a href="/eT/SIR/SIR2.html">2 Reproduction number</a><a href="/eT/SIR/SIR3.html">3 Estimating the parameters</a><a href="/eT/SIR/SIR4.html">4 Implementing the model</a><a href="/eT/SIR/SIR5.html">5 Update December 2020</a></div></div>\n'
